--- 
abstract: "[One line description of module's purpose here]"
author: Tomohiro IKEBE  C<< <ikebe@shebang.jp> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WebService-Livedoor-Auth
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  Class::ErrorHandler: 0
  Digest::HMAC_SHA1: 0
  LWP::UserAgent: 0
  Params::Validate: 0
  Scalar::Util: 0
  URI: 0
version: 0.01
